name: Plant Tree CI

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Plant a tree in the garden
      run: node index.js > GARDEN.md

    - name: Plant a tree in the park
      run: node index.js > plant-tree-park/PARK.md

    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Commit change & Push
      run: |
          git config user.name 'amirisback'
          git config user.email 'faisalamircs@gmail.com'
          git commit -am "plant some tree 🌳"
          git push
